const express = require("express");
const Item = require("../models/item");
const security = require("../middleware/security");
const router = express.Router();
//security.requireAuthenticatedUser

// endpoint to get items generated by user
router.get("/me", security.requireAuthenticatedUser, async (req, res, next) => {
  try {
    //send json response to client with all of the user-owned item instances in an array
    const { user } = res.locals;
    const items = await Item.listItemForUser(user);
    return res.status(201).json({ items });
  } catch (err) {
    next(err);
  }
});

router.get("/", security.requireAuthenticatedUser, async (req, res, next) => {
	try {
	  const inventoryId = req.query.inventory;
	  console.log(inventoryId);
	  const page = req.query.page;

	  const { user } = res.locals;
	  const items = await Item.listInventoryItems(inventoryId, page);
	  return res.status(201).json({ items });
	} catch (err) {
	  next(err);
	}
  });

router.get("/id/:itemId", security.requireAuthenticatedUser, async(req,res,next) => {
	try {
		const {itemId} = req.params

		const item = await Item.getItemById(itemId);
		
		return res.status(201).json({item});
	} catch (error) {
		next(error);
	}
})
  

// endpoint to create an item
router.post("/", security.requireAuthenticatedUser, async (req, res, next) => {
  try {
    const { user } = res.locals;
    const items = await Item.createItem({ item: req.body, user: user });
    return res.status(201).json({ items });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
